window.lang = {
  _db: {
    "404_DESCRIPTION": "您搜索的页面无法找到",
    "404_TITLE": "页面无法找到",
    "ALL_RIGHTS_RESERVED": "版权所有",
    "AM_I_INFECTED_LINK": "https:\/\/kas.pr\/cybermap_ww_win_kis_smmbuild.exe",
    "AM_I_INFECTED": "我的电脑被感染了吗?",
    "BUZZ_CTA_THREATPOST": "在Threadpost 博客阅读",
    "CONTINENT_AFRIKA": "非洲",
    "CONTINENT_ASIA": "亚洲",
    "CONTINENT_EUROPE": "欧洲",
    "CONTINENT_NORTH_AMERICA": "北美洲",
    "CONTINENT_OCEANIA": "大洋洲",
    "CONTINENT_SOUTH_AMERICA": "南美洲",
    "CONTINENT_WORLD": "世界",
    "CONTROL_DISABLE_DEMO_MODE": "关闭演示模式",
    "CONTROL_ENABLE_DEMO_MODE": "启动演示模式",
    "CONTROL_GLOBE_VIEW": "切换至全球视角",
    "CONTROL_PLANE_VIEW": "切换至平面视图",
    "CONTROL_TOGGLE_COLOR": "切换地图颜色",
    "CONTROL_ZOOM_IN": "放大",
    "CONTROL_ZOOM_OUT": "缩小",
    "COPYRIGHT": "2018 AO卡巴斯基实验室",
    "DATA_FROM_KASPERSKY_LAB": "根据卡巴斯基实验室数据",
    "META_DESCRIPTION": null,
    "META_KEYWORDS": null,
    "TITLE": "卡巴斯基网络威胁实时地图",
    "DETECTIONS_DISCOVERED": "从00:00 GMT起检测发现",
    "DOWNLOAD_TRIAL": "下载试用",
    "DOWNLOAD_TRIAL_LINK_ANDROID": "https:\/\/app.appsflyer.com\/com.kms.free?pid=smm&c=cn_cybermap",
    "DOWNLOAD_TRIAL_LINK_MAC": "https:\/\/www.kaspersky.com.cn\/downloads\/thank-you\/mac-security-free-trial?redef=1&reseller=cn_cybermap_trd_ona_smm__onl_b2c_cybm_lnk____kism___",
    "DOWNLOAD_TRIAL_LINK_WIN": "https:\/\/www.kaspersky.com.cn\/downloads\/thank-you\/internet-security-free-trial?redef=1&reseller=cn_cybermap_trd_ona_smm__onl_b2c_cybm_lnk____kismd___",
    "FOOTER_DOWNLOAD_SCREENSAVER": null,
    "GDPR_OK_BUTTON": "接受",
    "GDPR_TEXT": "我们使用 Cookie 来改善您对我们网站的体验。如果使用并进一步浏览本网站，即表明您接受某些浏览活动可以记录在 Cookie 中。单击 <a href =\"https:\/\/www.kaspersky.com.cn\/web-privacy-policy\"target =\"_ blank\">更多信息<\/a>，可以获得有关在本网站上使用 Cookie 的详细信息。",
    "HEADER_TITLE": "<b>网络威胁<\/b> 实时地图",
    "KASPERSKY_WEBSITE": "https:\/\/www.kaspersky.com.cn\/",
    "LANG_NAME": "英语",
    "LINK_FB": "",
    "LINK_GOOGLE_PLUS": "",
    "LINK_LINKEDIN": "https:\/\/www.linkedin.com\/company\/9495538\/",
    "LINK_TWITTER": "",
    "LINK_VK": "https:\/\/www.weibo.com\/p\/1006061646000801\/home?from=page_100606&mod=TAB&is_all=1#place",
    "MAP_CITY_BER": "柏林",
    "MAP_CITY_CAI": "开罗",
    "MAP_CITY_DUB": "迪拜",
    "MAP_CITY_IST": "伊斯坦布尔",
    "MAP_CITY_JOH": "约翰尼斯堡",
    "MAP_CITY_LAX": "东京",
    "MAP_CITY_LON": "伦敦",
    "MAP_CITY_MAD": "马德里",
    "MAP_CITY_MIA": "迈阿密",
    "MAP_CITY_MOS": "莫斯科",
    "MAP_CITY_MUM": "孟买",
    "MAP_CITY_NAI": "内罗比",
    "MAP_CITY_NYC": "纽约市",
    "MAP_CITY_RIO": "里约热内卢",
    "MAP_CITY_ROM": "罗马",
    "MAP_CITY_STP": "圣彼得堡",
    "MAP_CITY_SYD": "悉尼",
    "MAP_COUNTRY_ABW": "阿鲁巴",
    "MAP_COUNTRY_AFG": "阿富汗",
    "MAP_COUNTRY_AGO": "安哥拉",
    "MAP_COUNTRY_AIA": "安圭拉岛",
    "MAP_COUNTRY_ALA": "阿兰群岛",
    "MAP_COUNTRY_ALB": "阿尔巴尼亚",
    "MAP_COUNTRY_ALL": "所有国家",
    "MAP_COUNTRY_AND": "安道尔",
    "MAP_COUNTRY_ANT": "荷属安的列斯",
    "MAP_COUNTRY_ARE": "阿拉伯联合酋长国",
    "MAP_COUNTRY_ARG": "阿根廷",
    "MAP_COUNTRY_ARM": "亚美尼亚",
    "MAP_COUNTRY_ASM": "美属萨摩亚",
    "MAP_COUNTRY_ATA": "南极洲",
    "MAP_COUNTRY_ATF": "法属南部领地",
    "MAP_COUNTRY_ATG": "安提瓜和巴布达",
    "MAP_COUNTRY_AUS": "澳大利亚",
    "MAP_COUNTRY_AUT": "奥地利",
    "MAP_COUNTRY_AZE": "阿塞拜疆",
    "MAP_COUNTRY_BDI": "布隆迪",
    "MAP_COUNTRY_BEL": "比利时",
    "MAP_COUNTRY_BEN": "贝宁",
    "MAP_COUNTRY_BES": "博内尔，圣尤斯特歇斯和萨巴",
    "MAP_COUNTRY_BFA": "布基纳法索",
    "MAP_COUNTRY_BGD": "孟加拉国",
    "MAP_COUNTRY_BGR": "保加利亚",
    "MAP_COUNTRY_BHR": "巴林岛",
    "MAP_COUNTRY_BHS": "巴哈马群岛",
    "MAP_COUNTRY_BIH": "波斯尼亚和黑塞哥维那（波黑）",
    "MAP_COUNTRY_BLM": "加勒比海圣巴特岛",
    "MAP_COUNTRY_BLR": "白俄罗斯",
    "MAP_COUNTRY_BLZ": "伯利兹城",
    "MAP_COUNTRY_BMU": "百慕大群岛",
    "MAP_COUNTRY_BOL": "玻利维亚",
    "MAP_COUNTRY_BRA": "巴西",
    "MAP_COUNTRY_BRB": "巴巴多斯",
    "MAP_COUNTRY_BRN": "文莱达鲁萨兰国",
    "MAP_COUNTRY_BTN": "不丹",
    "MAP_COUNTRY_BVT": "布维岛",
    "MAP_COUNTRY_BWA": "博茨瓦纳",
    "MAP_COUNTRY_CAF": "中非共和国",
    "MAP_COUNTRY_CAN": "加拿大",
    "MAP_COUNTRY_CCK": "科科斯（基林）群岛",
    "MAP_COUNTRY_CHE": "瑞士",
    "MAP_COUNTRY_CHL": "智利",
    "MAP_COUNTRY_CHN": "中国大陆",
    "MAP_COUNTRY_CIV": "科特迪瓦",
    "MAP_COUNTRY_CMR": "喀麦隆",
    "MAP_COUNTRY_COD": "刚果民主共和国",
    "MAP_COUNTRY_COG": "刚果共和国",
    "MAP_COUNTRY_COK": "库克群岛",
    "MAP_COUNTRY_COL": "哥伦比亚",
    "MAP_COUNTRY_COM": "科摩罗",
    "MAP_COUNTRY_CPV": "佛得角共和国",
    "MAP_COUNTRY_CRI": "哥斯达黎加",
    "MAP_COUNTRY_CUB": "古巴",
    "MAP_COUNTRY_CUW": "库拉索岛",
    "MAP_COUNTRY_CXR": "圣诞岛",
    "MAP_COUNTRY_CYM": "开曼群岛",
    "MAP_COUNTRY_CYP": "塞浦路斯",
    "MAP_COUNTRY_CZE": "捷克共和国",
    "MAP_COUNTRY_DEU": "德国",
    "MAP_COUNTRY_DJI": "吉布提",
    "MAP_COUNTRY_DMA": "多米尼加岛",
    "MAP_COUNTRY_DNK": "丹麦",
    "MAP_COUNTRY_DOM": "多米尼加共和国",
    "MAP_COUNTRY_DZA": "阿尔及利亚",
    "MAP_COUNTRY_ECU": "厄瓜多尔",
    "MAP_COUNTRY_EGY": "埃及",
    "MAP_COUNTRY_ERI": "厄立特里亚",
    "MAP_COUNTRY_ESH": "西撒哈拉",
    "MAP_COUNTRY_ESP": "西班牙",
    "MAP_COUNTRY_EST": "爱沙尼亚",
    "MAP_COUNTRY_ETH": "埃塞俄比亚",
    "MAP_COUNTRY_FIN": "芬兰",
    "MAP_COUNTRY_FJI": "斐济",
    "MAP_COUNTRY_FLK": "福克兰群岛（马尔维纳斯群岛）",
    "MAP_COUNTRY_FRA": "法国",
    "MAP_COUNTRY_FRO": "法罗群岛",
    "MAP_COUNTRY_FSM": "密克罗尼西亚联邦",
    "MAP_COUNTRY_GAB": "加蓬",
    "MAP_COUNTRY_GBR": "英国",
    "MAP_COUNTRY_GEO": "格鲁吉亚",
    "MAP_COUNTRY_GGY": "格恩西",
    "MAP_COUNTRY_GHA": "加纳",
    "MAP_COUNTRY_GIB": "直布罗陀",
    "MAP_COUNTRY_GIN": "几内亚",
    "MAP_COUNTRY_GLP": "瓜德罗普岛",
    "MAP_COUNTRY_GMB": "冈比亚",
    "MAP_COUNTRY_GNB": "几内亚比绍",
    "MAP_COUNTRY_GNQ": "赤道几内亚",
    "MAP_COUNTRY_GRC": "希腊",
    "MAP_COUNTRY_GRD": "格林纳达大使馆",
    "MAP_COUNTRY_GRL": "格陵兰",
    "MAP_COUNTRY_GTM": "危地马拉",
    "MAP_COUNTRY_GUF": "法属圭亚那",
    "MAP_COUNTRY_GUM": "关岛",
    "MAP_COUNTRY_GUY": "圭亚那",
    "MAP_COUNTRY_HKG": "中国香港 ",
    "MAP_COUNTRY_HMD": "赫德岛和麦克唐纳群岛",
    "MAP_COUNTRY_HND": "洪都拉斯",
    "MAP_COUNTRY_HRV": "克罗地亚",
    "MAP_COUNTRY_HTI": "海地",
    "MAP_COUNTRY_HUN": "匈牙利",
    "MAP_COUNTRY_IDN": "印度尼西亚",
    "MAP_COUNTRY_IMN": "英属地曼岛",
    "MAP_COUNTRY_IND": "印度",
    "MAP_COUNTRY_IOT": "英属印度洋领地",
    "MAP_COUNTRY_IRL": "爱尔兰",
    "MAP_COUNTRY_IRN": "伊朗",
    "MAP_COUNTRY_IRQ": "伊拉克",
    "MAP_COUNTRY_ISL": "冰岛",
    "MAP_COUNTRY_ISR": "以色列",
    "MAP_COUNTRY_ITA": "意大利",
    "MAP_COUNTRY_JAM": "牙买加",
    "MAP_COUNTRY_JEY": "泽西岛",
    "MAP_COUNTRY_JOR": "约旦",
    "MAP_COUNTRY_JPN": "日本",
    "MAP_COUNTRY_KAZ": "哈萨克斯坦",
    "MAP_COUNTRY_KEN": "肯尼亚",
    "MAP_COUNTRY_KGZ": "吉尔吉斯斯坦",
    "MAP_COUNTRY_KHM": "柬埔寨",
    "MAP_COUNTRY_KIR": "基里巴斯",
    "MAP_COUNTRY_KNA": "圣基茨和尼维斯",
    "MAP_COUNTRY_KOR": "韩国",
    "MAP_COUNTRY_KWT": "科威特",
    "MAP_COUNTRY_LAO": "老挝",
    "MAP_COUNTRY_LBN": "黎巴嫩",
    "MAP_COUNTRY_LBR": "利比里亚",
    "MAP_COUNTRY_LBY": "利比亚",
    "MAP_COUNTRY_LCA": "圣卢西亚岛",
    "MAP_COUNTRY_LIE": "列支敦士登",
    "MAP_COUNTRY_LKA": "斯里兰卡",
    "MAP_COUNTRY_LSO": "莱索托",
    "MAP_COUNTRY_LTU": "立陶宛",
    "MAP_COUNTRY_LUX": "卢森堡公国",
    "MAP_COUNTRY_LVA": "拉脱维亚",
    "MAP_COUNTRY_MAC": "中国澳门",
    "MAP_COUNTRY_MAF": "法属圣马丁",
    "MAP_COUNTRY_MAR": "摩洛哥",
    "MAP_COUNTRY_MCO": "摩纳哥",
    "MAP_COUNTRY_MDA": "摩尔多瓦",
    "MAP_COUNTRY_MDG": "马达加斯加",
    "MAP_COUNTRY_MDV": "马尔代夫",
    "MAP_COUNTRY_MEX": "墨西哥",
    "MAP_COUNTRY_MHL": "马绍尔群岛",
    "MAP_COUNTRY_MKD": "马其顿",
    "MAP_COUNTRY_MLI": "马里",
    "MAP_COUNTRY_MLT": "马尔他",
    "MAP_COUNTRY_MMR": "缅甸",
    "MAP_COUNTRY_MNE": "黑山共和国",
    "MAP_COUNTRY_MNG": "蒙古",
    "MAP_COUNTRY_MNP": "北马里亚纳群岛邦",
    "MAP_COUNTRY_MOZ": "莫桑比克",
    "MAP_COUNTRY_MRT": "毛里塔尼亚",
    "MAP_COUNTRY_MSR": "蒙特色拉特岛",
    "MAP_COUNTRY_MTQ": "马提尼克岛",
    "MAP_COUNTRY_MUS": "毛里求斯",
    "MAP_COUNTRY_MWI": "马拉维",
    "MAP_COUNTRY_MYS": "马来西亚",
    "MAP_COUNTRY_MYT": "马约特岛",
    "MAP_COUNTRY_NAM": "纳米比亚",
    "MAP_COUNTRY_NCL": "新克里多尼亚岛",
    "MAP_COUNTRY_NER": "尼日尔",
    "MAP_COUNTRY_NFK": "诺福克岛",
    "MAP_COUNTRY_NGA": "尼日利亚",
    "MAP_COUNTRY_NIC": "尼加拉瓜",
    "MAP_COUNTRY_NIU": "纽埃岛",
    "MAP_COUNTRY_NLD": "荷兰",
    "MAP_COUNTRY_NOR": "挪威",
    "MAP_COUNTRY_NPL": "尼泊尔",
    "MAP_COUNTRY_NRU": "瑙鲁",
    "MAP_COUNTRY_NZL": "新西兰",
    "MAP_COUNTRY_OMN": "阿曼",
    "MAP_COUNTRY_PAK": "巴基斯坦",
    "MAP_COUNTRY_PAN": "巴拿马",
    "MAP_COUNTRY_PCN": "皮特凯恩",
    "MAP_COUNTRY_PER": "秘鲁",
    "MAP_COUNTRY_PHL": "菲律宾",
    "MAP_COUNTRY_PLW": "帕劳群岛",
    "MAP_COUNTRY_PNG": "巴布亚新几内亚",
    "MAP_COUNTRY_POL": "波兰",
    "MAP_COUNTRY_PRI": "波多黎各",
    "MAP_COUNTRY_PRK": "朝鲜",
    "MAP_COUNTRY_PRT": "葡萄牙",
    "MAP_COUNTRY_PRY": "巴拉圭",
    "MAP_COUNTRY_PSE": "巴勒斯坦被占领土",
    "MAP_COUNTRY_PYF": "法属玻里尼西亚",
    "MAP_COUNTRY_QAT": "卡塔尔",
    "MAP_COUNTRY_REU": "留尼旺",
    "MAP_COUNTRY_ROU": "罗马尼亚",
    "MAP_COUNTRY_RUS": "俄罗斯",
    "MAP_COUNTRY_RWA": "卢旺达",
    "MAP_COUNTRY_SAU": "沙特阿拉伯",
    "MAP_COUNTRY_SDN": "苏丹",
    "MAP_COUNTRY_SEN": "塞内加尔",
    "MAP_COUNTRY_SGP": "新加坡",
    "MAP_COUNTRY_SGS": "南乔治亚岛和南桑威奇群岛",
    "MAP_COUNTRY_SHN": "圣赫勒拿岛、阿森松岛和特里斯坦—达库尼亚群岛",
    "MAP_COUNTRY_SJM": "斯瓦尔巴特群岛",
    "MAP_COUNTRY_SLB": "所罗门群岛",
    "MAP_COUNTRY_SLE": "塞拉利昂",
    "MAP_COUNTRY_SLV": "萨尔瓦多",
    "MAP_COUNTRY_SMR": "圣马力诺",
    "MAP_COUNTRY_SOM": "索马里",
    "MAP_COUNTRY_SPM": "圣皮埃尔岛及密克隆岛",
    "MAP_COUNTRY_SRB": "塞尔维亚",
    "MAP_COUNTRY_SSD": "南苏丹",
    "MAP_COUNTRY_STP": "圣多美与普林西比",
    "MAP_COUNTRY_SUR": "苏里南",
    "MAP_COUNTRY_SVK": "斯洛伐克",
    "MAP_COUNTRY_SVN": "斯洛文尼亚",
    "MAP_COUNTRY_SWE": "瑞典",
    "MAP_COUNTRY_SWZ": "斯威士兰",
    "MAP_COUNTRY_SXM": "圣马丁岛",
    "MAP_COUNTRY_SYC": "塞舌尔",
    "MAP_COUNTRY_SYR": "叙利亚共和国",
    "MAP_COUNTRY_TCA": "特克斯和凯科斯群岛",
    "MAP_COUNTRY_TCD": "乍得",
    "MAP_COUNTRY_TGO": "多哥",
    "MAP_COUNTRY_THA": "泰国",
    "MAP_COUNTRY_TJK": "塔吉克斯坦",
    "MAP_COUNTRY_TKL": "托克劳",
    "MAP_COUNTRY_TKM": "土库曼斯坦",
    "MAP_COUNTRY_TLS": "东帝汶",
    "MAP_COUNTRY_TON": "汤加",
    "MAP_COUNTRY_TTO": "特立尼达和多巴哥",
    "MAP_COUNTRY_TUN": "突尼斯",
    "MAP_COUNTRY_TUR": "土耳其",
    "MAP_COUNTRY_TUV": "图瓦卢",
    "MAP_COUNTRY_TWN": "中国台湾",
    "MAP_COUNTRY_TZA": "坦桑尼亚",
    "MAP_COUNTRY_UGA": "乌干达",
    "MAP_COUNTRY_UKR": "乌克兰",
    "MAP_COUNTRY_UMI": "美国本土外小岛屿",
    "MAP_COUNTRY_URY": "乌拉圭",
    "MAP_COUNTRY_USA": "美国",
    "MAP_COUNTRY_UZB": "乌兹别克斯坦",
    "MAP_COUNTRY_VAT": "教廷（梵蒂冈城国）",
    "MAP_COUNTRY_VCT": "圣文森特和格林纳丁斯",
    "MAP_COUNTRY_VEN": "委内瑞拉",
    "MAP_COUNTRY_VGB": "英属维尔京群岛",
    "MAP_COUNTRY_VIR": "美属维尔京群岛",
    "MAP_COUNTRY_VNM": "越南",
    "MAP_COUNTRY_VUT": "瓦努阿图",
    "MAP_COUNTRY_WLF": "瓦利斯群岛和富图纳群岛",
    "MAP_COUNTRY_WSM": "萨摩亚",
    "MAP_COUNTRY_XKX": "科索沃",
    "MAP_COUNTRY_YEM": "也门",
    "MAP_COUNTRY_ZAF": "南非",
    "MAP_COUNTRY_ZMB": "赞比亚",
    "MAP_COUNTRY_ZWE": "津巴布韦",
    "MENU_BUZZ": "网络口碑",
    "MENU_DATA_SOURCES": "数据来源",
    "MENU_MAP": "地图",
    "MENU_SHARE_LABEL": "分享",
    "MENU_STATISTICS": "统计",
    "MENU_WIDGET": "窗口小部件",
    "META_COPYRIGHT": "AO 卡巴斯基实验室版权所有",
    "META_DESCRIPTION_BUZZ": "网络口碑 | 点击这里查明您是否处于网络攻击环境下",
    "META_DESCRIPTION_MAP": "地图 | 点击这里查明您是否处于网络攻击环境下",
    "META_DESCRIPTION_STATS": "统计 | 点击这里查明您是否处于网络攻击环境下",
    "META_DESCRIPTION_SUBSYSTEMS": "数据来源 | 点击这里查明您是否处于网络攻击环境下",
    "META_DESCRIPTION_TOS": "服务条款 | 点击这里查明您是否处于网络攻击环境下",
    "META_DESCRIPTION_WIDGET": "窗口小部件 | 点击这里查明您是否处于网络攻击环境下",
    "META_KEYWORDS_BUZZ": "网络口碑, 网络地图、网络战争、网络攻击、攻击",
    "META_KEYWORDS_MAP": "地图, 网络地图、网络战争、网络攻击、攻击",
    "META_KEYWORDS_STATS": "统计, 网络地图、网络战争、网络攻击、攻击",
    "META_KEYWORDS_SUBSYSTEMS": "数据来源, 网络地图、网络战争、网络攻击、攻击",
    "META_KEYWORDS_TOS": "服务条款, 网络地图、网络战争、网络攻击、攻击",
    "META_KEYWORDS_WIDGET": "窗口小部件, 网络地图、网络战争、网络攻击、攻击",
    "MORE_DETAILS": "更多详情",
    "MOST_ATTACKED_COUNTRY": "最易受到攻击的国家和地区",
    "NUMBER_SYMBOL": "#",
    "PRIVACY_POLICY": "隐私策略",
    "PRIVACY_POLICY_URL": "https:\/\/www.kaspersky.com.cn\/web-privacy-policy",
    "SCREENSAVER_CPU": null,
    "SCREENSAVER_DOWNLOAD_MAC": null,
    "SCREENSAVER_DOWNLOAD_TITLE": null,
    "SCREENSAVER_DOWNLOAD_WIN_X64": null,
    "SCREENSAVER_DOWNLOAD_WIN_X86": null,
    "SCREENSAVER_GPU": null,
    "SCREENSAVER_REQUIREMENTS": null,
    "SHARE_DATA": "分享数据",
    "SOCIAL_HASH_TAGS": "#网络安全地图 #网络安全 #网络战争",
    "SOCIAL_LINK": "https:\/\/cybermap.kaspersky.com\/cn\/",
    "SOCIAL_TEXT": "点击这里查明您的电脑是否处于网络攻击环境下",
    "STATISTICS_BOTNET_ACTIVITY": "僵尸网络活动",
    "STATISTICS_DETECTIONS_PER_SECOND": "每秒检测",
    "STATISTICS_HISTORY": "历史统计",
    "STATISTICS_IN_THE_LAST": "最后一次",
    "STATISTICS_INFECTED_MAIL": "被感染邮件",
    "STATISTICS_LAST_MONTH": "上个月",
    "STATISTICS_LAST_WEEK": "上周",
    "STATISTICS_LOCAL_INFECTIONS": "局部感染",
    "STATISTICS_MONTH": "月份",
    "STATISTICS_MOST_INFECTED_TODAY": "今日多数感染",
    "STATISTICS_NETWORK_ATTACKS": "网络袭击",
    "STATISTICS_NO_DATA": "无资料",
    "STATISTICS_ON_DEMAND_SCAN": "自定义扫描",
    "STATISTICS_PER_COUNTRY": "按国家",
    "STATISTICS_REAL_TIME": "实时",
    "STATISTICS_SEE_HISTORICAL_DATA": "查看历史数据",
    "STATISTICS_SPAM": "垃圾邮件",
    "STATISTICS_TIME_PERIOD": "时间周期",
    "STATISTICS_TOP": "顶部",
    "STATISTICS_TOTALS_RESET": "在每日0:00:00 GMT检测全部复位",
    "STATISTICS_VULNERABILITIES": "漏洞",
    "STATISTICS_WEB_THREATS": "网络威胁",
    "STATISTICS_WEEK": "周",
    "STATISTICS_WORLDWIDE": "全球范围",
    "SUBSYSTEMS_ESSENTIAL_PROTECTION": "对个人电脑进行最基本的保护，使其免受恶意软件袭击",
    "SUBSYSTEMS_ESSENTIAL_PROTECTION_LINK": "https:\/\/www.kaspersky.com.cn\/downloads\/thank-you\/total-security-free-trial?redef=1&reseller=cn_cybermap_trd_ona_smm__onl_b2c_cybm_lnk____ktsmd___",
    "SUBTITLE": "网络威胁实时地图",
    "TERMS_AND_CONDITIONS_BODY": "使用该网站意味着您同意受该等条件和条款的约束。AO卡巴斯基实验室(下文简称卡巴斯基实验室)保留以下权利：在任何时候自行决定变更使用条款或修改任何网站功能，无需另行通知。如果在发生任何更改后您继续使用该网站，则视作您已经接受该等变更。若不同意所有使用条款，请不要使用该网站。<br\/>卡巴斯基实验室拥有所有权利，包括该网站的独家权利或其他各种权利。卡巴斯基实验室拥有所有必要权利，包括知识产权，以及发表材料和信息的许可权，包括但不限于网站内的文本、图片、图形、视频、音频内容以及电脑代码（及内容）。<br\/>卡巴斯基实验室在此授予您查看和使用网站的权利，但其内容仅可用于信息性的、个人的或非商业用途。<br\/>对于卡巴斯基实验室因该等目的专门在网站上分享的内容，您可以下载、保存在您电脑或分享，但前提是：（1）不会删除任何专有权告示，（2）下载内容仅用于个人、非商业用途，不会重新传播，且（3）不会对该等内容进行任何修改，不会对内容进行歪曲或贬低。.<br\/>禁止对网站内容进行使用条款内未明确提出的任何形式的传播、出版或复制，除非前文提到的限制条件被适用法律明确禁止。<br\/><br\/>本网站提供的任何内容就是指“当前的含义”，并以任何形式进行明示或暗示保证或提出条件，包括但不限于默保证或适销性条款，适合特殊目的或未侵权等。<br\/>在适用法律允许的最大范围内，在任何情况下权利持有人都无需对任何特别的、偶然的、惩罚的、间接的或后续损失负责，无论是因使用网站内容引起或是以其他任何方式与网站内容产生关联。<br\/><br\/>© 2018 AO 卡巴斯基实验室版权所有。软件及任何相关文件均属版权产品，受版权法以及国际版权合约以及其他知识产权法律和合约保护。<br\/><br\/>",
    "TERMS_AND_CONDITIONS_INTRO": "致所有用户的重要法律告示：请在开始使用该网站前详细阅读以下使用条款。",
    "TERMS_AND_CONDITIONS_LAST_UPDATE": " 最后修正时间2015.08.18",
    "TERMS_AND_CONDITIONS_TITLE": "网站使用条款。",
    "TERMS_OF_SERVICE": "服务条款",
    "THREATS_URL": "https:\/\/threats.kaspersky.com\/en\/threat\/",
    "TITLE_BUZZ": "网络口碑 | 卡巴斯基网络威胁实时地图",
    "TITLE_MAP": "地图 | 卡巴斯基网络威胁实时地图",
    "TITLE_STATS": "统计 | 卡巴斯基网络威胁实时地图",
    "TITLE_SUBSYSTEMS": "数据来源 | 卡巴斯基网络威胁实时地图",
    "TITLE_TOS": "服务条款 | 卡巴斯基网络威胁实时地图",
    "TITLE_WIDGET": "窗口小部件 | 卡巴斯基网络威胁实时地图",
    "WIDGET_COLOR_THEME": "色彩主题",
    "WIDGET_DARK_THEME": "深色",
    "WIDGET_DESCRIPTION": "通过配置下方参数在您的网站添加网络地图，并生成最终 HTML代码。",
    "WIDGET_EMAIL_TOPIC": "网络地图窗口小部件安装",
    "WIDGET_HEIGHT": "身高",
    "WIDGET_LANGUAGE": "语言",
    "WIDGET_LIGHT_THEME": "浅色",
    "WIDGET_MAIL_THIS_CODE": "邮件发送该代码",
    "WIDGET_TAG_RENDER_DESCRIPTION": "在想要使用窗口小部件的地方插入该标签",
    "WIDGET_TITLE": "网络地图窗口小部件",
    "WIDGET_TYPE": "类型",
    "WIDGET_TYPE_DYNAMIC": "动态",
    "WIDGET_TYPE_STATIC": "静态",
    "WIDGET_WIDTH": "宽度"
  },

  languages: (function () {
    var o = ["de", "en", "es", "fr", "it", "ja", "pt", "ru", "tr", "cn"];
    return o.map(function (e) {
      return e[0]
    }).sort();
  }()),

  lang: function () {
    return 'cn';
  },

  getText: function (id) {
    return this._db[id];
  }
}